debug: false

permissions:
  punish: "punish.use"
  mute: "punish.mute"
  temp-mute: "punish.temp-mute"
  ban: "punish.ban"
  temp-ban: "punish.temp-ban"
  no-proof: "punish.no-proof"

broadcast:
  BAN: true
  IPBAN: true
  TEMPBAN: true
  MUTE: true
  IPMUTE: true
  TEMPMUTE: true